### ISSUE TITLE
Firmware collection 

### ISSUE THREAD

**Issue by sp2ong** [OK2MOP/MD1702-tools#1]
Maybe a good idea would be to set up a directory in which would be the firmware files that were released for DM-1702 /DM-X?

**Comment by OK2MOP** [comment]
It is already available in a discussion topic I participate in. But I am not really sure with the legality of such repo, so I did not place it here. It is available with stock CPS on https://drive.google.com/drive/folders/1iGy_f1ZVdTSFbh4BkZNjL_9iM0dSJVzK
