### ISSUE TITLE
Reverse engineering firmware

### ISSUE THREAD

**Issue by sp2ong** [OK2MOP/MD1702-tools#2]
Maybe you know this github where exist reverse engineering firmware for radios GD-77, GD-77S, RD-5R, MD-760, DM-1801 https://github.com/talentraspel/GD-77

and start writing firmware on opensource code:
https://github.com/hamdv/OpenGD77

**Comment by OK2MOP** [comment]
Sorry, but the firmware is more similar to the one with patches of md380-tools, but there are significant differences, trust me, I played several weeks with disassember to look into it. GD-77 is based on a different CPU/memory layout
